[workspace]
members = [
    "nakago",
    "nakago/derive",
    "nakago_axum",
    "nakago_sea_orm",
    "examples/*",
]
default-members = ["nakago", "nakago/derive", "nakago_axum", "nakago_sea_orm"]

[patch.crates-io]
nakago = { path = "./nakago" }
nakago-axum = { path = "./nakago_axum" }
nakago-derive = { path = "./nakago/derive" }
nakago-sea-orm = { path = "./nakago_sea_orm" }

[profile.release]
strip = true      # Automatically strip symbols from the binary.
opt-level = "z"   # Optimize for size.
lto = true        # Link time optimization.
codegen-units = 1 # Allow for maximum size reduction optimizations.
