# Docker Compose config for example projects
version: "3.1"

services:
    postgres:
        image: postgres
        container_name: async_graphql_postgres
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - ${DATABASE_PORT}:5432
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    redis:
        image: redis
        container_name: async_graphql_redis
        ports:
            - 6379:6379

volumes:
    postgres_data:
