[tasks.setup]
script = '''
    echo # installing git hooks
    pre-commit --version || pip install pre-commit
    pre-commit install || echo "failed to install git hooks!" 1>&2

    echo # things required for `cargo make test`
    cargo install cargo-nextest

    echo # things required by `cargo make pre-commit`
    cargo install cargo-spellcheck

    echo # things required by `cargo make coverage`
    rustup component add llvm-tools-preview
    cargo install cargo-llvm-cov

    echo # things required by `cargo make audit`
    cargo install cargo-audit
'''

[tasks.check]
command = "cargo"
args = [
    "clippy",
    "--tests",
    "--examples",
    "--all-targets",
    "--all-features",
    "--workspace",
]

[tasks.test]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = ["nextest", "run", "--all-features", "--workspace", "${@}"]

[tasks.test-ci]
env = { "RUST_LOG" = "info", "RUN_MODE" = "ci" }
command = "cargo"
args = ["nextest", "run", "--all-features", "--workspace"]

[tasks.docs]
command = "cargo"
args = [
    "doc",
    "--no-deps",
    "--all-features",
    "--document-private-items",
    "--workspace",
    "--examples",
]

[tasks.cov]
command = "cargo"
args = ["llvm-cov", "${@}"]

[tasks.audit]
command = "cargo"
args = ["audit"]

[tasks.timings]
script = '''
    cargo clean
    cargo build --release --quiet --timings
    xdg-open /target/cargo-timings/cargo-timing.html
'''

[tasks.pre-commit]
script = '''
    cargo make test
    cargo make docs
    cargo spellcheck fix
    cargo spellcheck reflow
'''
