version: "3.1"

services:
    api:
        image: async-graphql
        container_name: async_graphql
        depends_on:
            - redis
        ports:
            - 3000:3000
        environment:
            REDIS_URL: redis:6380
