version: "3.1"

services:
    api:
        image: async-graphql
        container_name: async_graphql
        depends_on:
            - redis
            - postgres
        ports:
            - 8010:8010
        environment:
            REDIS_URL: redis:6380
