[package]
name = "nakago-async-graphql"
version = "0.15.0"
authors = ["Brandon Konkle <brandon@konkle.us>"]
edition = "2021"
description = "An Async-GraphQL integration for Nakago"
documentation = "https://docs.rs/nakago/"
homepage = "https://github.com/bkonkle/nakago"
repository = "https://github.com/bkonkle/nakago"
license = "MIT"

[dependencies]
anyhow = "1.0"
async-graphql = { version = "6.0", features = ["chrono", "dataloader"] }
async-graphql-axum = "6.0"
async-trait = "0.1"
axum = { version = "0.7", features = ["macros"] }
derive-new = "0.5"
fake = { version = "2.4", features = ['derive', 'chrono', 'http', 'uuid'] }
figment = { version = "0.10", features = ["env"] }
hyper = "1.0"
log = "0.4"
nakago = "0.14"
nakago-axum = "0.16"
nakago-derive = "0.8"
pretty_env_logger = "0.5"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"

[dev-dependencies]
fake = { version = "2.4", features = ['derive', 'chrono', 'http', 'uuid'] }
mockall = "0.11"
pretty_assertions = "1.2"
