[package]
name = "nakago-async-graphql"
version = "0.17.0"
authors = ["Brandon Konkle <brandon@konkle.us>"]
edition = "2021"
description = "An Async-GraphQL integration for Nakago"
documentation = "https://docs.rs/nakago/"
homepage = "https://github.com/bkonkle/nakago"
repository = "https://github.com/bkonkle/nakago"
license = "MIT"

[dependencies]
anyhow = "1.0"
async-graphql = { git = "https://github.com/bkonkle/async-graphql.git", branch = "update-http-axum", features = [
    "chrono",
    "dataloader",
] }
async-graphql-axum = { git = "https://github.com/bkonkle/async-graphql.git", branch = "update-http-axum" }
async-trait = "0.1"
axum = { version = "0.7", features = ["macros"] }
derive-new = "0.6"
fake = { version = "2.9", features = [
    'derive',
    'chrono',
    'http',
    'uuid',
], git = "https://github.com/cksac/fake-rs.git" }
figment = { version = "0.10", features = ["env"] }
hyper = "1.0"
log = "0.4"
nakago = "0.17"
nakago-axum = "0.17"
nakago-derive = "0.8"
pretty_env_logger = "0.5"
rand = "0.8"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"

[dev-dependencies]
mockall = "0.11"
pretty_assertions = "1.2"
